# Generated by Django 4.1.7 on 2023-03-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expressions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstOperand', models.CharField(max_length=10)),
                ('operator', models.CharField(max_length=1)),
                ('secondOperand', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(verbose_name='Date Posted')),
            ],
        ),
    ]
