# Generated by Django 4.1.7 on 2023-03-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressions',
            name='firstOperand',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expressions',
            name='secondOperand',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expressions',
            name='total',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
