# Generated by Django 4.1.7 on 2023-03-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootout', '0003_alter_expressions_firstoperand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressions',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
