# Generated by Django 4.1.7 on 2023-03-18 02:16
from django.utils import timezone

from django.db import migrations

from shootout.models import Expressions


def create_expressions(apps, schema_editor):
    ex1 = Expressions()
    ex1.firstOperand = 2.0
    ex1.secondOperand = 5.0
    ex1.operator = "+"
    ex1.total = 7.0
    ex1.date_created = timezone.now()
    ex1.save()

    ex1 = Expressions()
    ex1.firstOperand = 10.0
    ex1.secondOperand = 12.0
    ex1.operator = "+"
    ex1.total = 22.0
    ex1.date_created = timezone.now()
    ex1.save()

    ex1 = Expressions()
    ex1.firstOperand = 10.0
    ex1.secondOperand = 5.0
    ex1.operator = "-"
    ex1.total = 5.0
    ex1.date_created = timezone.now()
    ex1.save()

    ex1 = Expressions()
    ex1.firstOperand = 21.0
    ex1.secondOperand = 6.0
    ex1.operator = "-"
    ex1.total = 15.0
    ex1.date_created = timezone.now()
    ex1.save()

    ex1 = Expressions()
    ex1.firstOperand = 57.0
    ex1.secondOperand = 2.0
    ex1.operator = "-"
    ex1.total = 55.0
    ex1.date_created = timezone.now()
    ex1.save()

    ex1 = Expressions()
    ex1.firstOperand = 4.0
    ex1.secondOperand = 5.0
    ex1.operator = "*"
    ex1.total = 20.0
    ex1.date_created = timezone.now()
    ex1.save()

    ex1 = Expressions()
    ex1.firstOperand = 10.0
    ex1.secondOperand = 10.0
    ex1.operator = "*"
    ex1.total = 100.0
    ex1.date_created = timezone.now()
    ex1.save()

    ex1 = Expressions()
    ex1.firstOperand = 10.0
    ex1.secondOperand = 2.0
    ex1.operator = "/"
    ex1.total = 5.0
    ex1.date_created = timezone.now()
    ex1.save()

    ex1 = Expressions()
    ex1.firstOperand = 24.0
    ex1.secondOperand = 10.0
    ex1.operator = "/"
    ex1.total = 2.4
    ex1.date_created = timezone.now()
    ex1.save()

    ex1 = Expressions()
    ex1.firstOperand = 10.0
    ex1.secondOperand = 2.0
    ex1.operator = "%"
    ex1.total = 0.0
    ex1.date_created = timezone.now()
    ex1.save()

    ex1 = Expressions()
    ex1.firstOperand = 20.0
    ex1.secondOperand = 3.0
    ex1.operator = "%"
    ex1.total = 2.0
    ex1.date_created = timezone.now()
    ex1.save()

    ex1 = Expressions()
    ex1.firstOperand = 2.0
    ex1.secondOperand = 3.0
    ex1.operator = "**"
    ex1.total = 8.0
    ex1.date_created = timezone.now()
    ex1.save()

    ex1 = Expressions()
    ex1.firstOperand = 5.0
    ex1.secondOperand = 2.0
    ex1.operator = "**"
    ex1.total = 25.0
    ex1.date_created = timezone.now()
    ex1.save()

    ex1 = Expressions()
    ex1.firstOperand = 5.0
    ex1.secondOperand = 0.0
    ex1.operator = "/"
    ex1.total = None
    ex1.date_created = timezone.now()
    ex1.save()

    ex1 = Expressions()
    ex1.firstOperand = 20.0
    ex1.secondOperand = 0.0
    ex1.operator = "/"
    ex1.total = None
    ex1.date_created = timezone.now()
    ex1.save()

class Migration(migrations.Migration):

    dependencies = [
        ('shootout', '0004_alter_expressions_total'),
    ]

    operations = [
        migrations.RunPython(create_expressions)
    ]


