# Generated by Django 4.1.7 on 2023-02-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
