# Generated by Django 4.1.7 on 2023-02-24 18:01
from time import timezone

from django.db import migrations
from django.utils import timezone
from blog.models import Blog, Comments


def create_blog_posts(apps, schema_editor):
    blog1 = Blog()
    blog1.title = "Exploring the Metaverse"
    blog1.author = "Thomas Stackpole"
    blog1.posted = timezone.now()
    blog1.content = """
            With the world what it is these days, you can see why people might be itching 
            for an alternate reality—a way to reboot the system and start fresh. That’s the 
            appeal of virtual realms: They’re places where power can be inverted, disappointments 
            escaped, and capitalist inequities left behind for something more exciting, malleable, and meaningful.
            It’s no wonder, then, that online universes like Fortnite and Roblox currently attract nearly 400 
            million users, and others like Decentraland and the Sandbox are growing rapidly. The market for them 
            will soon be worth more than $1 trillion, estimates show. Facebook has changed its name to Meta to 
            signal its belief in a virtual future. Microsoft is preparing for workplaces populated by digital 
            avatars. Fashion brands from Nike to Gucci are designing clothes and accessories for the metaverse. J.P. 
            Morgan and Samsung have set up shop in Decentraland. On Roblox players can operate their own Forever 21 
            stores and even sell their own designs in them. Many companies are making big bets on the metaverse (even 
            if most people still aren’t quite sure what it is).
        """
    blog1.imageUrl = "metaverse.png"
    blog1.save()

    comment1 = Comments()
    comment1.blog = blog1
    comment1.commenter = "Billy"
    comment1.email = "Billy@example.com"
    comment1.content = "wow this is the coolest thing everrrrrrrrr"
    comment1.posted = timezone.now()
    comment1.save()

    comment1 = Comments()
    comment1.blog = blog1
    comment1.commenter = "Tim"
    comment1.email = "Tim@example.com"
    comment1.content = "I love Penguins"
    comment1.posted = timezone.now()
    comment1.save()

    comment1 = Comments()
    comment1.blog = blog1
    comment1.commenter = "Johnny"
    comment1.email = "Johnny@example.com"
    comment1.content = "I think the metaverse is fake"
    comment1.posted = timezone.now()
    comment1.save()

    comment1 = Comments()
    comment1.blog = blog1
    comment1.commenter = "Billy"
    comment1.email = "Billy@example.com"
    comment1.content = "wow this is the coolest thing everrrrrrrrr"
    comment1.posted = timezone.now()
    comment1.save()

    blog2 = Blog()
    blog2.title = "What Is the Metaverse, Exactly?"
    blog2.author = "wired.com"
    blog2.posted = timezone.now()
    blog2.content = """
                    It's been nearly six months since Facebook announced it was rebranding to Meta and
                    would focus its future on the upcoming metaverse. In the time since, what that term
                    means hasn't gotten any clearer. Meta is building a VR social platform, Roblox is
                    facilitating user-generated video games, and some companies are offering up little
                    more than broken game worlds that happen to have NFTs attached.
                    Because the metaverse is largely unbuilt, there is little agreement on how it will work.
                    Broadly speaking, however, the metaverse is a digital ecosystem built on various kinds of 3D technology, real-time collaboration software and blockchain-based decentralized finance tools.
                    Factors such as the degree of interoperability among virtual worlds, data portability, governance and user interfaces will depend on how the metaverse pans out.
                    Lauren Lubetsky, senior manager at Bain & Company, speaking in a session on the metaverse at the 2022 MIT Platform Strategy Summit, outlined three possible scenarios:
                    The metaverse remains a domain of niche applications, used by consumers for entertainment and gaming but stopping well short of an all-encompassing virtual reality.
                    The metaverse is controlled by large competing ecosystems -- for example, Apple and Android meta worlds -- with limited interoperability.
                    The metaverse is a dynamic, open and interoperable space, much like the internet but in 3D.
        """

    blog2.imageUrl = "metaverse2.avif"
    blog2.save()

    comment1 = Comments()
    comment1.blog = blog2
    comment1.commenter = "Billy"
    comment1.email = "Billy@example.com"
    comment1.content = "wow this is the coolest thing everrrrrrrrr"
    comment1.posted = timezone.now()
    comment1.save()

    comment1 = Comments()
    comment1.blog = blog2
    comment1.commenter = "Tim"
    comment1.email = "Tim@example.com"
    comment1.content = "I love Penguins"
    comment1.posted = timezone.now()
    comment1.save()

    comment1 = Comments()
    comment1.blog = blog2
    comment1.commenter = "Johnny"
    comment1.email = "Johnny@example.com"
    comment1.content = "I think the metaverse is fake"
    comment1.posted = timezone.now()
    comment1.save()

    comment1 = Comments()
    comment1.blog = blog2
    comment1.commenter = "Billy"
    comment1.email = "Billy@example.com"
    comment1.content = "wow this is the coolest thing everrrrrrrrr"
    comment1.posted = timezone.now()
    comment1.save()

    blog3 = Blog()
    blog3.title = "What are the Dangers of the Metaverse?"
    blog3.author = "Dr Mark van Rijmenam"
    blog3.posted = timezone.now()
    blog3.content = """
                    Technology is neutral. It can bring prosperity to humanity or bring pain and destruction to society. The
                    metaverse will not be any different. We can expect any of the crimes committed in the real world to take
                    place, and potentially explode, on the immersive internet. After all, criminals will be active anywhere
                    there is money to be made, and the metaverse will be an infinite blue ocean full of countless
                    opportunities for consumers, creators, and organizations to make money.
                    Leaders will need to confront if their organizations are equipped with the essential tools to detect, 
                    contain and eliminate malicious code for metaverse projects. They also need to define what incident 
                    response looks like in the metaverse. What would a breach look like? How would the brand communicate 
                    and respond?
                    Leaders need to understand and create frameworks for collaborations to execute incident response efficiently 
                    because the answers to these questions will require support inside and outside of metaverse platforms.
        """
    blog3.imageUrl = "metaverse3.webp"
    blog3.save()

    comment1 = Comments()
    comment1.blog = blog3
    comment1.commenter = "Billy"
    comment1.email = "Billy@example.com"
    comment1.content = "wow this is the coolest thing everrrrrrrrr"
    comment1.posted = timezone.now()
    comment1.save()

    comment1 = Comments()
    comment1.blog = blog3
    comment1.commenter = "Tim"
    comment1.email = "Tim@example.com"
    comment1.content = "I love Penguins"
    comment1.posted = timezone.now()
    comment1.save()

    comment1 = Comments()
    comment1.blog = blog3
    comment1.commenter = "Johnny"
    comment1.email = "Johnny@example.com"
    comment1.content = "I think the metaverse is fake"
    comment1.posted = timezone.now()
    comment1.save()

    comment1 = Comments()
    comment1.blog = blog3
    comment1.commenter = "Billy"
    comment1.email = "Billy@example.com"
    comment1.content = "wow this is the coolest thing everrrrrrrrr"
    comment1.posted = timezone.now()
    comment1.save()

    blog4 = Blog()
    blog4.title = "1969 Moon Landing"
    blog4.author = "History.com"
    blog4.posted = timezone.now()
    blog4.content = """
    On July 20, 1969, American astronauts Neil Armstrong (1930-2012) and Edwin "Buzz" Aldrin (1930-) became the first 
    humans ever to land on the moon. About six-and-a-half hours later, Armstrong became the first person to walk on the 
    moon. As he took his first step, Armstrong famously said, "That's one small step for man, one giant leap for mankind.
    "The Apollo 11 mission occurred eight years after President John F. Kennedy (1917-1963) announced a national goal of 
    landing a man on the moon by the end of the 1960s. Apollo 17, the final manned moon mission, took place in 1972.
    WATCH: Moon Landing: The Lost Tapes on HISTORY Vault 
    JFK's Pledge Leads to Start of Apollo Program
    The American effort to send astronauts to the moon had its origins in an appeal President Kennedy made to a special 
    joint session of Congress on May 25, 1961: "I believe this nation should commit itself to achieving the goal, before 
    this decade is out, of landing a man on the moon and returning him safely to Earth." 
    """
    blog4.imageUrl = "moon.webp"
    blog4.save()

    comment1 = Comments()
    comment1.blog = blog4
    comment1.commenter = "Billy"
    comment1.email = "Billy@example.com"
    comment1.content = "wow this is the coolest thing everrrrrrrrr"
    comment1.posted = timezone.now()
    comment1.save()

    comment1 = Comments()
    comment1.blog = blog4
    comment1.commenter = "Tim"
    comment1.email = "Tim@example.com"
    comment1.content = "I love Penguins"
    comment1.posted = timezone.now()
    comment1.save()

    comment1 = Comments()
    comment1.blog = blog4
    comment1.commenter = "Johnny"
    comment1.email = "Johnny@example.com"
    comment1.content = "I think the metaverse is fake"
    comment1.posted = timezone.now()
    comment1.save()

    comment1 = Comments()
    comment1.blog = blog4
    comment1.commenter = "Billy"
    comment1.email = "Billy@example.com"
    comment1.content = "wow this is the coolest thing everrrrrrrrr"
    comment1.posted = timezone.now()
    comment1.save()

    blog5 = Blog()
    blog5.title = "GooseFeet Gear: Started a Decade Ago, When a Hiker Got Cold Feet!"
    blog5.author = "Maria Weidich"
    blog5.posted = timezone.now()
    blog5.content = """
    Ben Smith had cold feet. Literally. That’s the short story behind GooseFeet Gear, makers of ultralight goose down socks, pillows, and balaclavas, among other clothing items.   
    It took just one sub-freezing night on the Appalachian Trail for Ben to rethink the quality of his gear. As a self-described poor college student at the time, the gear Ben actually wanted exceeded his price range. But, what he lacked in currency, he made up for in cleverness.
    It was 2010, and Ben was a 20 year old Industrial and Material Engineering student at Georgia Institute of Technology. Crafting his own backpacking and hiking gear came naturally to Ben. 
    “It’s basically manufacturing meets material science,” he said of his academic interests. “Which corresponds nicely to what we do at GooseFeet Gear!”
    “I knew that my feet were always the first to get cold, so down socks were an obvious solution!”
    Another obvious solution was to use nature’s best insulator, goose down. GooseFeet Gear fills its ultralight clothing and accessories with DownTek — 850+ fill power, water repellent, ethically sourced goose down, processed in Ohio.  
    “We were using goose down to make socks for your feet, so we mashed it together to create GooseFeet,” Ben said. 
    Once he got the hang of making the down socks, he shared pictures of his finished products on multiple online backpacking forums. (This was pre-Instagram). 
    “People started asking me what I would charge to make them a pair,” Ben said. “I had enough requests that I had to make patterns for various sizes.” 
    """
    blog5.imageUrl = "feet.webp"
    blog5.save()

    comment1 = Comments()
    comment1.blog = blog5
    comment1.commenter = "Billy"
    comment1.email = "Billy@example.com"
    comment1.content = "wow this is the coolest thing everrrrrrrrr"
    comment1.posted = timezone.now()
    comment1.save()

    comment1 = Comments()
    comment1.blog = blog5
    comment1.commenter = "Tim"
    comment1.email = "Tim@example.com"
    comment1.content = "I love Penguins"
    comment1.posted = timezone.now()
    comment1.save()

    comment1 = Comments()
    comment1.blog = blog5
    comment1.commenter = "Johnny"
    comment1.email = "Johnny@example.com"
    comment1.content = "I think the metaverse is fake"
    comment1.posted = timezone.now()
    comment1.save()

    comment1 = Comments()
    comment1.blog = blog5
    comment1.commenter = "Billy"
    comment1.email = "Billy@example.com"
    comment1.content = "wow this is the coolest thing everrrrrrrrr"
    comment1.posted = timezone.now()
    comment1.save()

class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_alter_blog_imageurl'),
    ]

    operations = [
        migrations.RunPython(create_blog_posts)
    ]
